import type { SecurityFinding } from "@/lib/domain/types";
import type { SecurityRule } from "@/lib/rules/types";

/**
 * OWASP ASVS 5.0.0 기반의 자동화 가능한 정적 위험 신호 카탈로그.
 *
 * ASVS의 345개 요구사항 전체가 정규식으로 검증 가능한 것은 아니다. 이 목록은
 * 소스/설정만으로 근거를 남길 수 있는 요구사항을 17개 장 전체에서 선별한
 * 보수적 SAST 규칙이다. 런타임·설계·운영 검증이 필요한 요구사항은 스캔 결과에서
 * 별도 미검사 범위로 고지한다.
 *
 * 요구사항 문구는 복제하지 않고 탐지 목적에 맞게 재서술했다.
 */

export const ASVS_VERSION = "5.0.0";

export const ASVS5_CHAPTER_NAMES: Record<`V${number}`, string> = {
  V1: "Encoding and Sanitization",
  V2: "Validation and Business Logic",
  V3: "Web Frontend Security",
  V4: "API and Web Service",
  V5: "File Handling",
  V6: "Authentication",
  V7: "Session Management",
  V8: "Authorization",
  V9: "Self-contained Tokens",
  V10: "OAuth and OIDC",
  V11: "Cryptography",
  V12: "Secure Communication",
  V13: "Configuration",
  V14: "Data Protection",
  V15: "Secure Coding and Architecture",
  V16: "Security Logging and Error Handling",
  V17: "WebRTC",
};

export interface AsvsStaticSignal {
  key: string;
  ruleId: string;
  chapter: `V${number}`;
  asvsSections: string[];
  severity: SecurityFinding["severity"];
  cwe: string;
  cvss: number;
  category: string;
  title: string;
  titleKo: string;
  impact: string;
  remediation: string;
  pattern: RegExp;
  filePattern?: RegExp;
  requiresContent?: RegExp;
  safeContentPattern?: RegExp;
  safeWindowPattern?: RegExp;
  excludeLinePattern?: RegExp;
  windowBefore?: number;
  windowAfter?: number;
}

const signal = (
  index: number,
  value: Omit<AsvsStaticSignal, "ruleId">
): AsvsStaticSignal => ({
  ...value,
  ruleId: `ASVS5-${String(index).padStart(3, "0")}`,
});

export const ASVS5_STATIC_SIGNALS: AsvsStaticSignal[] = [
  signal(1, {
    key: "dynamic-regexp",
    chapter: "V1",
    asvsSections: ["V1.2"],
    severity: "medium",
    cwe: "CWE-1333",
    cvss: 5.3,
    category: "Encoding and Sanitization",
    title: "사용자 입력으로 검색 규칙(정규식)을 만들어요",
    titleKo: "입력값으로 만드는 정규식",
    impact: "누군가 처리에 아주 오래 걸리는 패턴을 보내면, 서버가 그 요청에 묶여 다른 요청을 처리하지 못할 수 있어요.",
    remediation: "사용자 입력을 정규식으로 쓰지 말고 일반 글자 검색으로 바꾸세요. 꼭 필요하면 허용한 패턴만 쓰고 입력 길이를 제한하세요.",
    pattern: /new\s+RegExp\s*\([^)]*(?:req\.|params|query|body|searchParams|input)/i,
  }),
  signal(2, {
    key: "dynamic-template",
    chapter: "V1",
    asvsSections: ["V1.2", "V1.5"],
    severity: "high",
    cwe: "CWE-1336",
    cvss: 8.1,
    category: "Encoding and Sanitization",
    title: "사용자 입력을 화면 템플릿 코드로 바로 만들어요",
    titleKo: "입력값으로 만드는 서버 템플릿(템플릿 인젝션)",
    impact: "입력에 템플릿 문법이 들어 있으면 서버에서 실행되어, 서버 데이터가 드러나거나 원하지 않는 코드가 실행될 수 있어요.",
    remediation: "템플릿은 코드에 미리 만들어 두고, 사용자 입력은 템플릿에 넣는 값(데이터)으로만 전달하세요.",
    pattern: /(?:compile|renderString|from_string)\s*\([^)]*(?:req\.|params|query|body|input)/i,
  }),
  signal(3, {
    key: "mass-assignment",
    chapter: "V2",
    asvsSections: ["V2.1", "V2.2"],
    severity: "high",
    cwe: "CWE-915",
    cvss: 7.5,
    category: "Validation and Business Logic",
    title: "요청 내용을 통째로 DB에 저장해요",
    titleKo: "사용자가 바꾸면 안 되는 값까지 저장되는 처리(대량 할당)",
    impact: "사용자가 요청에 role, ownerId, price 같은 값을 끼워 넣으면, 권한·데이터 주인·가격처럼 서버만 정해야 하는 값이 바뀔 수 있어요.",
    remediation: "요청 내용을 먼저 검사(스키마 검증)하고, 사용자가 바꿔도 되는 값만 골라 create/update에 넘기세요.",
    pattern: /\b(?:create|update|insert|save|set)\s*\(\s*(?:req\.body|request\.body|body|payload|data)\s*\)/i,
    safeWindowPattern: /(?:pick|omit|schema|safeParse|parse|validate|whitelist|allowedFields)/i,
    windowBefore: 5,
  }),
  signal(4, {
    key: "trusted-business-fields",
    chapter: "V2",
    asvsSections: ["V2.3", "V2.4"],
    severity: "medium",
    cwe: "CWE-602",
    cvss: 6.5,
    category: "Validation and Business Logic",
    title: "권한이나 가격 같은 중요한 값을 요청에서 그대로 받아요",
    titleKo: "중요한 값(권한·가격)을 요청에서 받는 처리",
    impact: "요청을 조작하면 권한, 데이터 주인, 가격 같은 값을 사용자가 원하는 대로 정할 수 있어요.",
    remediation: "권한은 로그인 정보에서, 가격은 서버에 저장된 정보에서 다시 가져와 쓰세요. 요청에 온 값은 쓰지 마세요.",
    pattern: /(?:role|isAdmin|ownerId|userId|price|amount|paid|status)\s*[:=].*(?:req\.body|body\.|payload\.|formData|searchParams)/i,
  }),
  signal(5, {
    key: "blank-opener",
    chapter: "V3",
    asvsSections: ["V3.2"],
    severity: "low",
    cwe: "CWE-1022",
    cvss: 3.1,
    category: "Web Frontend Security",
    title: "새 창으로 연 페이지가 원래 탭을 바꿀 수 있어요",
    titleKo: "새 창 링크의 원래 탭 보호 누락(탭내빙)",
    impact: "새 창으로 열린 외부 페이지가 window.opener로 원래 탭을 가짜 페이지(피싱)로 바꿀 수 있어요.",
    remediation: "target=\"_blank\" 링크에 rel=\"noopener noreferrer\"를 추가하세요.",
    pattern: /target\s*=\s*["'{]?_blank/i,
    safeWindowPattern: /rel\s*=\s*["'{][^\n}]*(?:noopener|noreferrer)/i,
    filePattern: /\.(?:tsx?|jsx?|html|vue|svelte)$/i,
  }),
  signal(6, {
    key: "postmessage-wildcard",
    chapter: "V3",
    asvsSections: ["V3.4"],
    severity: "medium",
    cwe: "CWE-346",
    cvss: 5.4,
    category: "Web Frontend Security",
    title: "브라우저 메시지를 받을 곳을 정하지 않고 보내요",
    titleKo: "브라우저 메시지(postMessage) 받는 곳 제한 누락",
    impact: "메시지에 담긴 정보가 의도하지 않은 다른 사이트로 전달될 수 있어요.",
    remediation: "postMessage의 두 번째 값을 \"*\" 대신 메시지를 받을 사이트의 정확한 https 주소로 바꾸세요.",
    pattern: /\.postMessage\s*\([^\n]*,\s*["'`]\*["'`]\s*\)/i,
  }),
  signal(7, {
    key: "message-origin",
    chapter: "V3",
    asvsSections: ["V3.4"],
    severity: "medium",
    cwe: "CWE-346",
    cvss: 5.4,
    category: "Web Frontend Security",
    title: "받은 브라우저 메시지가 어디서 왔는지 확인하지 않아요",
    titleKo: "받은 브라우저 메시지의 보낸 곳 확인 누락",
    impact: "다른 사이트가 보낸 메시지를 내 사이트가 보낸 명령처럼 처리할 수 있어요.",
    remediation: "메시지를 처리하기 전에 event.origin이 허용한 사이트 주소인지 확인하고, 아니면 무시하세요.",
    pattern: /addEventListener\s*\(\s*["']message["']/i,
    safeContentPattern: /(?:event|e)\.origin\s*(?:===|!==)|allowedOrigins?\.includes/i,
  }),
  signal(8, {
    key: "browser-token-storage",
    chapter: "V3",
    asvsSections: ["V3.5"],
    severity: "medium",
    cwe: "CWE-922",
    cvss: 5.4,
    category: "Web Frontend Security",
    title: "로그인 토큰을 브라우저 저장소(localStorage)에 보관해요",
    titleKo: "브라우저 저장소에 보관한 로그인 토큰",
    impact: "화면에서 다른 스크립트가 실행되는 문제(XSS)가 함께 있으면, 그 스크립트가 토큰을 읽어 가 로그인 상태를 빼앗을 수 있어요.",
    remediation: "가능하면 토큰 대신 HttpOnly·Secure·SameSite를 설정한 쿠키로 로그인 상태를 유지하세요.",
    pattern: /(?:localStorage|sessionStorage)\.setItem\s*\(\s*["'`](?:token|accessToken|refreshToken|jwt|session)/i,
  }),
  signal(9, {
    key: "cors-credentials-wildcard",
    chapter: "V4",
    asvsSections: ["V4.1", "V4.2"],
    severity: "high",
    cwe: "CWE-942",
    cvss: 8.1,
    category: "API and Web Service",
    title: "로그인 정보를 허용하면서 모든 사이트의 요청을 받아요",
    titleKo: "너무 넓게 열린 다른 사이트 접근 허용(CORS)",
    impact: "설정 방식에 따라 다른 사이트가 로그인한 사용자의 권한으로 내 API 응답을 읽을 수 있어요.",
    remediation: "허용할 사이트 주소를 목록으로 정하고 그 주소만 허용하세요. 요청에 온 Origin 값을 그대로 돌려주지 마세요.",
    pattern: /(?:origin\s*:\s*["'`]\*["'`]|Access-Control-Allow-Origin["'`\s,:]+\*)/i,
    requiresContent: /(?:credentials\s*:\s*true|Access-Control-Allow-Credentials["'`\s,:]+true)/i,
  }),
  signal(10, {
    key: "graphql-dev-features",
    chapter: "V4",
    asvsSections: ["V4.3"],
    severity: "low",
    cwe: "CWE-215",
    cvss: 3.7,
    category: "API and Web Service",
    title: "운영 GraphQL 서버에 개발용 탐색 기능이 켜져 있어요",
    titleKo: "켜져 있는 GraphQL 개발용 기능",
    impact: "누구나 API 구조와 요청할 수 있는 항목을 한눈에 볼 수 있어서, 공격할 곳을 찾기 쉬워져요.",
    remediation: "운영 환경에서는 playground와 introspection 설정을 꺼 주세요(false).",
    pattern: /(?:introspection|playground|graphiql)\s*:\s*true/i,
    requiresContent: /graphql|apollo|mercurius/i,
  }),
  signal(11, {
    key: "unbounded-json-body",
    chapter: "V4",
    asvsSections: ["V4.4"],
    severity: "low",
    cwe: "CWE-770",
    cvss: 3.7,
    category: "API and Web Service",
    title: "API 요청 크기 제한이 정해져 있지 않아요",
    titleKo: "요청 크기 제한 누락",
    impact: "아주 큰 요청이 들어오면 서버 메모리와 처리 시간을 많이 써서 사이트가 느려질 수 있어요.",
    remediation: "JSON·폼 처리 설정에 필요한 만큼의 최대 크기를 정하세요(예: express.json({ limit: \"100kb\" })).",
    pattern: /(?:express|app|router)\.json\s*\(\s*\)|bodyParser\.json\s*\(\s*\)/i,
    safeWindowPattern: /limit\s*:/i,
  }),
  signal(12, {
    key: "upload-original-name",
    chapter: "V5",
    asvsSections: ["V5.2", "V5.3"],
    severity: "high",
    cwe: "CWE-434",
    cvss: 7.5,
    category: "File Handling",
    title: "업로드한 파일 이름을 검사 없이 저장 경로에 써요",
    titleKo: "업로드 파일 이름을 그대로 쓰는 저장 경로",
    impact: "조작한 파일 이름으로 허용한 폴더 밖의 파일을 덮어쓰거나, 실행될 수 있는 파일을 저장할 수 있어요.",
    remediation: "저장할 파일 이름은 서버가 무작위로 만들고, 파일 형식(MIME)·확장자·크기·실제 내용을 함께 확인하세요.",
    pattern: /(?:originalname|originalFilename|file\.name).*(?:writeFile|move|rename|join|destination)|(?:writeFile|move|rename|join)[^(]*\([^\n]*(?:originalname|originalFilename|file\.name)/i,
    safeWindowPattern: /(?:basename|randomUUID|uuid|sanitize|allowedTypes|mime)/i,
    windowBefore: 4,
    windowAfter: 2,
  }),
  signal(13, {
    key: "archive-extract-all",
    chapter: "V5",
    asvsSections: ["V5.4"],
    severity: "high",
    cwe: "CWE-22",
    cvss: 7.5,
    category: "File Handling",
    title: "압축 파일을 경로 확인 없이 한꺼번에 풀어요",
    titleKo: "압축 해제 경로 확인 누락(Zip Slip)",
    impact: "조작한 압축 파일이 풀리면서 정해진 폴더 밖의 파일을 덮어쓸 수 있어요.",
    remediation: "압축 안의 파일마다 풀릴 경로를 계산해, 정해진 폴더 안인지 확인한 뒤에만 푸세요.",
    pattern: /(?:extractAllTo|extractall|unzipper\.Extract|admZip\.extractAllTo)\s*\(/i,
    safeWindowPattern: /(?:resolve|normalize|startsWith|\.\.\/|isWithin)/i,
    windowBefore: 5,
  }),
  signal(14, {
    key: "weak-password-hash",
    chapter: "V6",
    asvsSections: ["V6.2", "V6.3"],
    severity: "critical",
    cwe: "CWE-916",
    cvss: 9.1,
    category: "Authentication",
    title: "비밀번호를 빠른 일반 해시로 바꿔 저장해요",
    titleKo: "빠른 해시로 저장한 비밀번호",
    impact: "비밀번호 저장소가 유출되면 원래 비밀번호를 대량으로 알아내기 쉬워요.",
    remediation: "비밀번호는 Argon2id, scrypt, 충분한 비용을 준 bcrypt·PBKDF2처럼 비밀번호 저장용 방식과 사용자마다 다른 salt로 저장하세요.",
    pattern: /(?:md5|sha1|sha256|sha512|createHash\s*\(\s*["'`](?:md5|sha1|sha256|sha512))[^(\n]*(?:password|passwd|pwd)/i,
  }),
  signal(15, {
    key: "plaintext-password-compare",
    chapter: "V6",
    asvsSections: ["V6.2"],
    severity: "critical",
    cwe: "CWE-256",
    cvss: 9.1,
    category: "Authentication",
    title: "비밀번호를 원래 글자 그대로 비교해요",
    titleKo: "원래 글자 그대로 다루는 비밀번호",
    impact: "비밀번호가 원래 글자 그대로 저장되어 있을 가능성이 커요. 저장소나 로그가 유출되면 사용자 비밀번호가 바로 드러나요.",
    remediation: "비밀번호는 bcrypt 같은 비밀번호 저장용 방식으로 저장하고, 비교할 때는 그 라이브러리의 verify(compare) 함수를 쓰세요.",
    pattern: /(?:password|passwd|pwd)\s*(?:===|==)\s*(?:req\.body|body\.|input\.|user\.(?:password|passwd|pwd))/i,
    excludeLinePattern: /(?:hash|digest|bcrypt|argon|scrypt|verify|compare)/i,
  }),
  signal(16, {
    key: "auth-no-throttle",
    chapter: "V6",
    asvsSections: ["V6.4"],
    severity: "medium",
    cwe: "CWE-307",
    cvss: 6.5,
    category: "Authentication",
    title: "로그인 처리 코드에서 시도 횟수 제한을 찾지 못했어요",
    titleKo: "로그인 반복 시도 제한 누락(코드)",
    impact: "누군가 비밀번호를 자동으로 계속 넣어 보거나, 유출된 계정 목록을 차례로 시험할 수 있어요.",
    remediation: "로그인 요청에 계정별·IP별 시도 횟수 제한을 넣고, 여러 번 틀리면 잠시 막거나 추가 확인을 요청하세요.",
    pattern: /(?:signIn|signin|login|authenticate)\s*(?:=|\(|:)|export\s+(?:async\s+)?function\s+POST/i,
    filePattern: /(?:auth|login|signin|session)[^/]*\.(?:tsx?|jsx?|py|go|rb|php|java|cs)$/i,
    safeContentPattern: /(?:rateLimit|rateLimiter|throttl|tooMany|429|lockout|attempts?)/i,
  }),
  signal(17, {
    key: "cookie-flags",
    chapter: "V7",
    asvsSections: ["V7.2", "V7.4"],
    severity: "medium",
    cwe: "CWE-614",
    cvss: 5.4,
    category: "Session Management",
    title: "로그인 쿠키에 보호 설정이 모두 있지는 않아요",
    titleKo: "로그인 쿠키 보호 설정 누락(코드)",
    impact: "화면 스크립트, 암호화되지 않은 연결, 다른 사이트의 요청을 통해 로그인 상태를 빼앗기거나 악용될 가능성이 커져요.",
    remediation: "로그인 쿠키를 만들 때 HttpOnly, Secure, SameSite를 모두 설정하고 Path를 필요한 범위로 제한하세요.",
    pattern: /(?:cookies?\.set|setCookie|Set-Cookie)[^(\n]*\([^\n]*(?:session|token|auth|sid)/i,
    safeWindowPattern: /httpOnly\s*:\s*true[\s\S]*secure\s*:\s*true[\s\S]*sameSite|secure\s*:\s*true[\s\S]*httpOnly\s*:\s*true[\s\S]*sameSite/i,
    windowAfter: 6,
  }),
  signal(18, {
    key: "token-in-url",
    chapter: "V7",
    asvsSections: ["V7.5"],
    severity: "high",
    cwe: "CWE-598",
    cvss: 7.5,
    category: "Session Management",
    title: "로그인 토큰을 주소(URL)에 담아 보내요",
    titleKo: "주소(URL)에 담긴 로그인 토큰",
    impact: "토큰이 브라우저 방문 기록, 서버 접속 기록, 분석 도구, 다른 사이트로 넘어가는 주소 정보(Referer)에 남을 수 있어요.",
    remediation: "로그인 토큰은 주소에 넣지 말고 안전한 쿠키나 Authorization 헤더로 보내세요.",
    pattern: /(?:[?&](?:token|access_token|session|jwt)=|searchParams\.(?:set|append)\s*\(\s*["'`](?:token|access_token|session|jwt))/i,
  }),
  signal(19, {
    key: "mutation-no-auth",
    chapter: "V8",
    asvsSections: ["V8.2", "V8.3"],
    severity: "medium",
    cwe: "CWE-862",
    cvss: 6.5,
    category: "Authorization",
    title: "데이터를 바꾸는 API에서 로그인·권한 확인을 찾지 못했어요",
    titleKo: "데이터 변경 API의 권한 확인 누락 가능성",
    impact: "로그인하지 않았거나 권한이 없는 사람이 데이터를 만들거나 고치거나 지울 수 있어요. 다른 파일에서 확인하고 있다면 문제가 아닐 수 있어요.",
    remediation: "데이터를 바꾸는 모든 API에서 처리 전에 로그인한 사용자인지, 그 데이터를 바꿀 권한이 있는지 서버에서 확인하세요.",
    pattern: /export\s+(?:async\s+)?function\s+(?:POST|PUT|PATCH|DELETE)\b|router\.(?:post|put|patch|delete)\s*\(/i,
    filePattern: /(?:route|api|controller|handler|server)[^/]*\.(?:tsx?|jsx?|py|go|rb|php|java|cs)$/i,
    safeContentPattern: /(?:getCurrentUser|getServerSession|auth\s*\(|requireAuth|authorize|permission|currentUser|req\.user|session\.user|userId|ownerId|403|Unauthorized|Forbidden)/i,
  }),
  signal(20, {
    key: "client-admin-gate",
    chapter: "V8",
    asvsSections: ["V8.1", "V8.4"],
    severity: "high",
    cwe: "CWE-602",
    cvss: 7.5,
    category: "Authorization",
    title: "관리자인지를 브라우저에 저장된 값으로만 판단해요",
    titleKo: "브라우저에서만 하는 관리자 확인",
    impact: "사용자가 브라우저 저장값을 바꾸면 관리자 화면이나 기능에 들어갈 수 있어요. 서버에서도 확인하고 있다면 화면만 열릴 수 있어요.",
    remediation: "화면의 관리자 확인은 보조로만 쓰고, 관리자 기능 API에서 서버가 관리자 권한을 다시 확인하게 하세요.",
    pattern: /(?:localStorage|sessionStorage).*(?:isAdmin|role|admin)|(?:isAdmin|role)\s*=.*(?:localStorage|sessionStorage)/i,
  }),
  signal(21, {
    key: "jwt-decode-only",
    chapter: "V9",
    asvsSections: ["V9.1", "V9.2"],
    severity: "critical",
    cwe: "CWE-345",
    cvss: 9.1,
    category: "Self-contained Tokens",
    title: "로그인 토큰(JWT)을 진짜인지 확인하지 않고 읽기만 해요",
    titleKo: "로그인 토큰(JWT) 서명 확인 누락",
    impact: "누군가 토큰 내용을 바꿔 다른 사용자나 관리자인 척해도 서버가 그대로 믿을 수 있어요.",
    remediation: "decode 대신, 신뢰하는 키와 허용할 서명 방식을 지정한 verify로 확인하세요. 발급자(issuer)·대상(audience)·만료 시간도 함께 확인하세요.",
    pattern: /(?:jwt\.)?decode\s*\([^)]*(?:token|jwt|authorization)/i,
    safeWindowPattern: /(?:jwt\.)?verify\s*\(/i,
    windowBefore: 4,
    windowAfter: 4,
  }),
  signal(22, {
    key: "jwt-algorithms",
    chapter: "V9",
    asvsSections: ["V9.1"],
    severity: "high",
    cwe: "CWE-347",
    cvss: 7.5,
    category: "Self-contained Tokens",
    title: "로그인 토큰(JWT)을 확인할 때 허용할 서명 방식을 정하지 않았어요",
    titleKo: "로그인 토큰(JWT) 서명 방식 제한 누락",
    impact: "라이브러리 설정에 따라 약한 서명 방식의 토큰이나 서명 방식을 속인 토큰이 통과할 수 있어요.",
    remediation: "verify를 부를 때 algorithms 목록(예: [\"HS256\"])을 지정하고, 토큰에 적힌 서명 방식을 그대로 믿지 마세요.",
    pattern: /(?:jwt\.)?verify\s*\([^\n]+\)/i,
    safeWindowPattern: /algorithms?\s*:/i,
    windowAfter: 3,
  }),
  signal(23, {
    key: "oauth-missing-state",
    chapter: "V10",
    asvsSections: ["V10.3", "V10.4"],
    severity: "high",
    cwe: "CWE-352",
    cvss: 7.5,
    category: "OAuth and OIDC",
    title: "소셜 로그인(OAuth) 요청에 위조 방지 값(state)이 보이지 않아요",
    titleKo: "소셜 로그인 위조 방지 값 누락",
    impact: "누군가 로그인 과정을 가로채거나 바꿔치기해서, 사용자를 공격자 계정에 로그인시키거나 계정을 잘못 연결할 수 있어요.",
    remediation: "로그인 요청마다 추측할 수 없는 state 값을 만들어 세션에 저장하고, 돌아온 값과 같은지 확인하세요. OIDC를 쓰면 nonce도 확인하세요.",
    pattern: /(?:response_type=code|\/authorize\?|authorizationUrl)/i,
    requiresContent: /oauth|oidc|openid|authorization/i,
    safeContentPattern: /(?:state|nonce)\s*[:=]|[?&](?:state|nonce)=/i,
  }),
  signal(24, {
    key: "oauth-no-pkce",
    chapter: "V10",
    asvsSections: ["V10.2", "V10.4"],
    severity: "medium",
    cwe: "CWE-345",
    cvss: 6.5,
    category: "OAuth and OIDC",
    title: "소셜 로그인(OAuth) 코드 교환에 PKCE가 보이지 않아요",
    titleKo: "소셜 로그인 코드 보호(PKCE) 누락",
    impact: "중간에 가로챈 로그인 코드(authorization code)를 다른 프로그램이 대신 쓸 수 있어요.",
    remediation: "로그인 요청에 S256 방식의 code_challenge를 넣고, 코드를 교환할 때 한 번만 쓰는 code_verifier를 보내세요.",
    pattern: /response_type\s*[=:]\s*["'`]code|response_type=code/i,
    requiresContent: /oauth|oidc|openid|authorize/i,
    safeContentPattern: /code_challenge|code_verifier|pkce/i,
  }),
  signal(25, {
    key: "weak-crypto",
    chapter: "V11",
    asvsSections: ["V11.2", "V11.3"],
    severity: "high",
    cwe: "CWE-327",
    cvss: 7.5,
    category: "Cryptography",
    title: "보안에 쓰면 안 되는 오래된 암호 방식을 써요",
    titleKo: "오래된 암호 방식 사용",
    impact: "약한 방식이라 데이터가 바뀌었는지 알아채지 못하거나, 암호화한 내용이 풀릴 수 있어요.",
    remediation: "용도에 맞는 최신 방식(예: 해시는 SHA-256 이상, 암호화는 AES-GCM)과 검증된 암호 라이브러리를 쓰세요.",
    pattern: /(?:createHash|createCipheriv|Cipher|getInstance)\s*\(\s*["'`](?:md5|sha-?1|des|rc4|aes[^"'`]*ecb)/i,
  }),
  signal(26, {
    key: "security-math-random",
    chapter: "V11",
    asvsSections: ["V11.1"],
    severity: "high",
    cwe: "CWE-338",
    cvss: 7.5,
    category: "Cryptography",
    title: "보안용 값을 예측할 수 있는 난수(Math.random)로 만들어요",
    titleKo: "예측 가능한 난수로 만든 보안 값",
    impact: "누군가 비밀번호 재설정 토큰, 인증번호, 세션 값을 짐작해 맞힐 수 있어요.",
    remediation: "보안용 값은 crypto.randomBytes나 crypto.randomUUID처럼 보안용 난수 함수로 만드세요.",
    pattern: /(?:token|otp|nonce|secret|session|reset|code)\w*\s*=.*Math\.random\s*\(|Math\.random\s*\([^\n]*(?:token|otp|nonce|secret|session|reset)/i,
  }),
  signal(27, {
    key: "fixed-iv",
    chapter: "V11",
    asvsSections: ["V11.3"],
    severity: "high",
    cwe: "CWE-329",
    cvss: 7.5,
    category: "Cryptography",
    title: "암호화할 때 쓰는 시작값(IV)이 고정돼 있어요",
    titleKo: "고정된 암호화 시작값(IV)",
    impact: "같은 내용을 암호화하면 같은 결과가 나와서, 암호화한 내용의 패턴이 드러날 수 있어요.",
    remediation: "암호화할 때마다 보안용 난수로 새 IV(nonce)를 만들고, AES-GCM처럼 변조 여부도 확인하는 방식을 쓰세요.",
    pattern: /(?:createCipheriv|AES\.new|Cipher\.getInstance)[^\n]*(?:Buffer\.alloc\([^)]*,\s*0\)|["'`](?:0{12,}|[0-9a-f]{16,})["'`])/i,
  }),
  signal(28, {
    key: "tls-validation-disabled",
    chapter: "V12",
    asvsSections: ["V12.2", "V12.3"],
    severity: "critical",
    cwe: "CWE-295",
    cvss: 9.1,
    category: "Secure Communication",
    title: "https 인증서 확인을 꺼 두었어요",
    titleKo: "꺼져 있는 https 인증서 확인",
    impact: "통신 중간에 있는 사람이 상대 서버인 척하고, 주고받는 로그인 정보와 데이터를 가로챌 수 있어요.",
    remediation: "인증서 확인 설정(rejectUnauthorized 등)을 다시 켜세요. 사설 인증서가 필요하면 그 인증서만 신뢰하도록 따로 등록하세요.",
    pattern: /rejectUnauthorized\s*:\s*false|verify\s*=\s*False|CERT_NONE|InsecureSkipVerify\s*:\s*true|NODE_TLS_REJECT_UNAUTHORIZED\s*=\s*["']?0/i,
  }),
  signal(29, {
    key: "plaintext-service-url",
    chapter: "V12",
    asvsSections: ["V12.1"],
    severity: "medium",
    cwe: "CWE-319",
    cvss: 6.5,
    category: "Secure Communication",
    title: "외부 서비스와 암호화되지 않은 http·ws 주소로 통신해요",
    titleKo: "암호화되지 않은 외부 통신",
    impact: "통신 중간에서 요청·응답 내용과 로그인 정보를 엿보거나 바꿀 수 있어요.",
    remediation: "외부 통신 주소를 https:// 또는 wss:// 로 바꾸세요.",
    pattern: /["'`](?:http|ws):\/\/(?!localhost|127\.0\.0\.1|0\.0\.0\.0|\[::1\])[^"'`\s]+/i,
    excludeLinePattern: /(?:example\.com|schema|namespace|xmlns|documentation|comment)/i,
  }),
  signal(30, {
    key: "production-debug",
    chapter: "V13",
    asvsSections: ["V13.1", "V13.4"],
    severity: "medium",
    cwe: "CWE-489",
    cvss: 5.3,
    category: "Configuration",
    title: "디버그나 자세한 오류 표시 설정이 켜져 있어요",
    titleKo: "운영 환경에서 켜진 디버그 설정",
    impact: "오류가 나면 코드 위치, 서버 경로, 설정값 같은 내부 정보가 사용자에게 보일 수 있어요.",
    remediation: "운영 설정에서 debug, 개발 모드, 자세한 오류 표시, playground를 끄세요.",
    pattern: /(?:DEBUG|debug|devTools|detailedErrors|showStack|stacktrace)\s*[:=]\s*(?:true|True|1|["']true["'])/i,
    filePattern: /(?:config|settings|\.env|application|next\.config|vite\.config|server)[^/]*$/i,
  }),
  signal(31, {
    key: "production-sourcemap",
    chapter: "V13",
    asvsSections: ["V13.1"],
    severity: "low",
    cwe: "CWE-540",
    cvss: 3.7,
    category: "Configuration",
    title: "운영 사이트에서 원본 소스(소스맵)가 공개될 수 있어요",
    titleKo: "공개되는 운영 소스맵",
    impact: "누구나 원본 코드와 내부 경로를 볼 수 있어서 약점을 찾기 쉬워져요.",
    remediation: "공개 배포에서는 브라우저 소스맵을 끄세요. 오류 분석에 필요하면 접근이 제한된 오류 수집 서비스에만 올리세요.",
    pattern: /(?:productionBrowserSourceMaps|sourcemap|sourceMap)\s*[:=]\s*true/i,
    filePattern: /(?:config|settings|next|vite|webpack|rollup)[^/]*\.(?:tsx?|jsx?|json|ya?ml|toml)$/i,
  }),
  signal(32, {
    key: "default-credential",
    chapter: "V13",
    asvsSections: ["V13.2"],
    severity: "critical",
    cwe: "CWE-1392",
    cvss: 9.8,
    category: "Configuration",
    title: "기본값이나 예시 비밀번호가 코드에 남아 있어요",
    titleKo: "기본값·예시 비밀번호 사용",
    impact: "널리 알려진 비밀번호라서, 그 비밀번호를 쓰는 계정이나 서비스에 누구나 로그인할 수 있어요.",
    remediation: "기본 계정과 예시 비밀번호를 지우고, 강한 비밀번호를 배포 서비스의 비밀 설정(환경변수)에 저장해 불러오세요.",
    pattern: /(?:password|passwd|pwd)\s*[:=]\s*["'`](?:admin|password|changeme|default|root|test123|123456)["'`]/i,
  }),
  signal(33, {
    key: "sensitive-log",
    chapter: "V14",
    asvsSections: ["V14.2", "V14.3"],
    severity: "high",
    cwe: "CWE-532",
    cvss: 7.5,
    category: "Data Protection",
    title: "로그에 비밀번호·토큰 같은 민감한 값이 남을 수 있어요",
    titleKo: "로그에 남는 민감한 값",
    impact: "로그를 볼 수 있는 사람이나 외부 로그 서비스에 로그인 정보와 민감한 정보가 보일 수 있어요.",
    remediation: "로그를 남기기 전에 비밀번호·토큰·쿠키 같은 값을 빼거나 가리고(마스킹), 필요한 값만 기록하세요.",
    pattern: /(?:console\.(?:log|info|debug|error)|logger\.(?:info|debug|error|warn)|print\s*\()[^\n]*(?:password|passwd|token|authorization|cookie|secret|ssn|credit.?card)/i,
  }),
  signal(34, {
    key: "pii-query-string",
    chapter: "V14",
    asvsSections: ["V14.1", "V14.2"],
    severity: "medium",
    cwe: "CWE-598",
    cvss: 5.3,
    category: "Data Protection",
    title: "민감한 값을 주소(URL)에 담아 보내요",
    titleKo: "주소(URL)에 담긴 민감한 값",
    impact: "그 값이 브라우저 방문 기록, 서버 접속 기록, 분석 도구, 다른 사이트로 넘어가는 주소 정보(Referer)에 남을 수 있어요.",
    remediation: "민감한 값은 주소 대신 요청 본문(body)에 담아 보내고, 로그와 분석 도구에 남지 않게 하세요.",
    pattern: /[?&](?:password|passwd|token|secret|ssn|credit_?card|resident_?number)=|searchParams\.(?:set|append)\s*\(\s*["'`](?:password|passwd|secret|ssn|credit_?card)/i,
  }),
  signal(35, {
    key: "unsafe-deserialization",
    chapter: "V15",
    asvsSections: ["V15.3"],
    severity: "critical",
    cwe: "CWE-502",
    cvss: 9.8,
    category: "Secure Coding and Architecture",
    title: "외부에서 받은 데이터를 안전하지 않은 방식으로 객체로 복원해요",
    titleKo: "안전하지 않은 데이터 복원(역직렬화)",
    impact: "조작한 데이터를 복원하는 과정에서 서버에서 원하지 않는 코드가 실행될 수 있어요.",
    remediation: "외부 데이터는 JSON 같은 단순한 형식으로 받고 스키마로 검사하세요. pickle.loads, unserialize 같은 객체 복원 함수는 외부 데이터에 쓰지 마세요.",
    pattern: /(?:pickle\.loads|yaml\.load\s*\(|unserialize\s*\(|ObjectInputStream\s*\(|BinaryFormatter|Marshal\.load)\s*[^\n]*(?:req|request|body|input|data|payload|file)/i,
  }),
  signal(36, {
    key: "dynamic-ssrf",
    chapter: "V15",
    asvsSections: ["V15.4"],
    severity: "high",
    cwe: "CWE-918",
    cvss: 8.2,
    category: "Secure Coding and Architecture",
    title: "사용자가 준 주소로 서버가 직접 요청을 보내요",
    titleKo: "서버가 대신 보내는 요청(SSRF) 가능성",
    impact: "누군가 서버를 통해, 외부에서는 닿을 수 없는 내부 서비스나 클라우드 설정 정보에 접근할 수 있어요.",
    remediation: "요청할 주소의 프로토콜·도메인·포트를 허용 목록으로 제한하고, 내부 IP와 DNS 재바인딩 우회를 막으세요.",
    pattern: /(?:fetch|axios\.(?:get|post|request)|requests?\.(?:get|post)|http\.(?:get|request))\s*\([^\n]*(?:req\.|request\.|params|query|body|input|url)/i,
    safeWindowPattern: /(?:allowlist|allowedHosts|safeFetch|isPrivate|isBlocked|new URL|validateUrl)/i,
    // 서버 설정(process.env.X)이나 상수 문자열로만 만든 주소는 사용자 입력이 아니다.
    // (예: fetch(process.env.MAIL_API_URL, ...) 의 "URL"을 입력으로 오인하지 않게)
    excludeLinePattern:
      /(?:fetch|axios\.(?:get|post|request)|requests?\.(?:get|post)|http\.(?:get|request))\s*\(\s*(?:process\.env\.[A-Za-z0-9_]+|["'`][^"'`$]*["'`])\s*[,)]/,
    windowBefore: 5,
  }),
  signal(37, {
    key: "prototype-pollution",
    chapter: "V15",
    asvsSections: ["V15.2"],
    severity: "high",
    cwe: "CWE-1321",
    cvss: 8.1,
    category: "Secure Coding and Architecture",
    title: "요청 내용을 기존 객체에 깊게 합쳐요",
    titleKo: "객체 기본값 변조(프로토타입 오염) 가능성",
    impact: "요청에 __proto__ 같은 이름을 넣으면 앱 전체 객체의 기본값이 바뀌어, 권한 확인 같은 처리가 틀어질 수 있어요.",
    remediation: "요청에서 받을 키를 스키마로 제한하고 __proto__·constructor·prototype 키는 버리세요. 안전한 병합 함수와 null prototype 객체를 쓰세요.",
    pattern: /(?:merge|defaultsDeep|deepMerge|Object\.assign)\s*\([^\n]*(?:req\.body|body|payload|input)/i,
    safeWindowPattern: /(?:schema|safeParse|validate|sanitize|__proto__|constructor|prototype)/i,
    windowBefore: 4,
  }),
  signal(38, {
    key: "error-stack-response",
    chapter: "V16",
    asvsSections: ["V16.1", "V16.2"],
    severity: "medium",
    cwe: "CWE-209",
    cvss: 5.3,
    category: "Security Logging and Error Handling",
    title: "내부 오류 내용을 API 응답으로 그대로 보내요",
    titleKo: "API 응답에 드러나는 오류 상세 정보",
    impact: "파일 경로, DB 조회문, 사용하는 라이브러리 같은 내부 정보가 보여 공격 준비에 쓰일 수 있어요.",
    remediation: "사용자에게는 일반 오류 메시지만 보내고, 자세한 원인은 접근이 제한된 서버 로그에만 남기세요.",
    pattern: /(?:res\.(?:json|send)|NextResponse\.json|Response\.json|return\s+json)\s*\([^\n]*(?:error|err)\.(?:stack|message|cause)/i,
  }),
  signal(39, {
    key: "empty-catch",
    chapter: "V16",
    asvsSections: ["V16.1"],
    severity: "low",
    cwe: "CWE-390",
    cvss: 3.3,
    category: "Security Logging and Error Handling",
    title: "오류가 나도 기록하지 않고 그냥 넘어가요",
    titleKo: "비어 있는 오류 처리(catch)",
    impact: "보안 관련 실패나 공격 흔적이 기록되지 않고, 앱이 잘못된 상태로 계속 동작할 수 있어요.",
    remediation: "예상한 오류만 골라 처리하고, 나머지는 민감한 값을 뺀 채 로그에 기록하세요.",
    pattern: /catch\s*(?:\([^)]*\))?\s*\{\s*\}/i,
  }),
  signal(40, {
    key: "webrtc-insecure-signaling",
    chapter: "V17",
    asvsSections: ["V17.3"],
    severity: "high",
    cwe: "CWE-319",
    cvss: 7.5,
    category: "WebRTC",
    title: "영상·음성 연결(WebRTC)을 준비하는 통신이 암호화되지 않아요",
    titleKo: "암호화되지 않은 WebRTC 연결 준비 통신",
    impact: "연결 정보가 중간에서 가로채이거나 바뀌어 통화 연결을 빼앗길 수 있어요.",
    remediation: "연결 준비(시그널링) 서버 주소를 wss:// 또는 https로 바꾸고, 로그인한 사용자만 메시지를 보낼 수 있게 하세요.",
    pattern: /["'`]ws:\/\/[^"'`\s]+/i,
    requiresContent: /RTCPeerConnection|getUserMedia|iceCandidate|RTCSessionDescription|webrtc/i,
  }),
  signal(41, {
    key: "webrtc-hardcoded-turn",
    chapter: "V17",
    asvsSections: ["V17.2", "V17.3"],
    severity: "high",
    cwe: "CWE-798",
    cvss: 7.5,
    category: "WebRTC",
    title: "영상·음성 중계 서버(TURN) 접속 정보가 화면 코드에 들어 있어요",
    titleKo: "화면 코드에 들어 있는 TURN 접속 정보",
    impact: "누구나 그 정보로 중계 서버를 몰래 써서 비용이 늘거나 서비스가 느려질 수 있어요.",
    remediation: "TURN 접속 정보는 코드에 넣지 말고, 로그인한 사용자에게 서버가 짧은 기간만 쓰는 값으로 만들어 주세요.",
    pattern: /(?:iceServers|turn:)[\s\S]{0,300}username\s*:[\s\S]{0,120}credential\s*:\s*["'`][^"'`]+["'`]/i,
    requiresContent: /RTCPeerConnection|iceServers|turn:/i,
  }),
];

export const ASVS5_RULE_IDS = ASVS5_STATIC_SIGNALS.map((s) => s.ruleId);

export const ASVS5_RULES: SecurityRule[] = ASVS5_STATIC_SIGNALS.map((s) => ({
  id: s.ruleId,
  family: s.ruleId,
  version: ASVS_VERSION,
  // 소스만 읽는 정적 신호이므로 모드 A(상위 모드 B/C에도 포함).
  mode: "A" as const,
  title: s.title,
  titleKo: s.titleKo,
  summaryKo: s.impact,
  severity: s.severity,
  standards: [
    ...s.asvsSections.map((id) => ({
      framework: "OWASP_ASVS" as const,
      version: ASVS_VERSION,
      id,
    })),
    { framework: "CWE" as const, id: s.cwe },
  ],
  appliesTo: ["web", "api", "baas"],
  selector: {
    all: [{ field: "source.access", op: "equals", value: "read_only" }],
  },
  methods: ["SAST"],
  prerequisites: { SAST: ["source_checkout"] },
  checks: [
    {
      id: `scan-${s.key}`,
      toolId: "static_web_analyzer",
      method: "SAST",
    },
  ],
  execution: {
    tier: "PASSIVE",
    target: "source_checkout",
    destructiveOperations: false,
  },
  remediation: {
    autoPatch: "branch_only",
    allowedPaths: ["app/**", "src/**", "server/**", "api/**", "config/**", "*.config.*"],
    productionChange: "not_applicable",
  },
  verificationRequiredChecks: [`scan-${s.key}`, "changed-code-scan"],
}));

const RULE_BY_KEY = new Map(ASVS5_STATIC_SIGNALS.map((s) => [s.key, s.ruleId]));

export function asvsRuleIdForSignal(key: string): string | null {
  return RULE_BY_KEY.get(key) ?? null;
}
