import type { SecurityFinding } from "@/lib/domain/types";
import type { SecurityRule } from "@/lib/rules/types";

/**
 * OWASP ASVS 5.0.0 기반의 자동화 가능한 정적 위험 신호 카탈로그.
 *
 * ASVS의 345개 요구사항 전체가 정규식으로 검증 가능한 것은 아니다. 이 목록은
 * 소스/설정만으로 근거를 남길 수 있는 요구사항을 17개 장 전체에서 선별한
 * 보수적 SAST 규칙이다. 런타임·설계·운영 검증이 필요한 요구사항은 스캔 결과에서
 * 별도 미검사 범위로 고지한다.
 *
 * 요구사항 문구는 복제하지 않고 탐지 목적에 맞게 재서술했다.
 */

export const ASVS_VERSION = "5.0.0";

export const ASVS5_CHAPTER_NAMES: Record<`V${number}`, string> = {
  V1: "Encoding and Sanitization",
  V2: "Validation and Business Logic",
  V3: "Web Frontend Security",
  V4: "API and Web Service",
  V5: "File Handling",
  V6: "Authentication",
  V7: "Session Management",
  V8: "Authorization",
  V9: "Self-contained Tokens",
  V10: "OAuth and OIDC",
  V11: "Cryptography",
  V12: "Secure Communication",
  V13: "Configuration",
  V14: "Data Protection",
  V15: "Secure Coding and Architecture",
  V16: "Security Logging and Error Handling",
  V17: "WebRTC",
};

export interface AsvsStaticSignal {
  key: string;
  ruleId: string;
  chapter: `V${number}`;
  asvsSections: string[];
  severity: SecurityFinding["severity"];
  cwe: string;
  cvss: number;
  category: string;
  title: string;
  titleKo: string;
  impact: string;
  remediation: string;
  pattern: RegExp;
  filePattern?: RegExp;
  requiresContent?: RegExp;
  safeContentPattern?: RegExp;
  safeWindowPattern?: RegExp;
  excludeLinePattern?: RegExp;
  windowBefore?: number;
  windowAfter?: number;
}

const signal = (
  index: number,
  value: Omit<AsvsStaticSignal, "ruleId">
): AsvsStaticSignal => ({
  ...value,
  ruleId: `ASVS5-${String(index).padStart(3, "0")}`,
});

export const ASVS5_STATIC_SIGNALS: AsvsStaticSignal[] = [
  signal(1, {
    key: "dynamic-regexp",
    chapter: "V1",
    asvsSections: ["V1.2"],
    severity: "medium",
    cwe: "CWE-1333",
    cvss: 5.3,
    category: "Encoding and Sanitization",
    title: "사용자 입력으로 정규식을 만들어 서비스 거부가 발생할 수 있습니다",
    titleKo: "동적 정규식 입력 검증 누락",
    impact: "공격자가 매우 오래 걸리는 정규식을 주입해 서버 처리 시간을 고갈시킬 수 있습니다.",
    remediation: "정규식 패턴을 허용 목록으로 제한하고 입력 길이와 실행 시간을 제한하세요.",
    pattern: /new\s+RegExp\s*\([^)]*(?:req\.|params|query|body|searchParams|input)/i,
  }),
  signal(2, {
    key: "dynamic-template",
    chapter: "V1",
    asvsSections: ["V1.2", "V1.5"],
    severity: "high",
    cwe: "CWE-1336",
    cvss: 8.1,
    category: "Encoding and Sanitization",
    title: "사용자 입력이 템플릿으로 직접 컴파일됩니다",
    titleKo: "서버 템플릿 인젝션",
    impact: "템플릿 엔진 문법이 실행되어 서버 데이터 노출이나 코드 실행으로 이어질 수 있습니다.",
    remediation: "사용자 입력은 템플릿 소스가 아니라 데이터 값으로만 전달하세요.",
    pattern: /(?:compile|renderString|from_string)\s*\([^)]*(?:req\.|params|query|body|input)/i,
  }),
  signal(3, {
    key: "mass-assignment",
    chapter: "V2",
    asvsSections: ["V2.1", "V2.2"],
    severity: "high",
    cwe: "CWE-915",
    cvss: 7.5,
    category: "Validation and Business Logic",
    title: "요청 본문 전체가 데이터 모델에 그대로 반영됩니다",
    titleKo: "대량 할당(Mass Assignment)",
    impact: "공격자가 role, ownerId, price 같은 서버 전용 필드를 임의로 변경할 수 있습니다.",
    remediation: "스키마 검증 후 허용한 필드만 명시적으로 선택해 create/update에 전달하세요.",
    pattern: /\b(?:create|update|insert|save|set)\s*\(\s*(?:req\.body|request\.body|body|payload|data)\s*\)/i,
    safeWindowPattern: /(?:pick|omit|schema|safeParse|parse|validate|whitelist|allowedFields)/i,
    windowBefore: 5,
  }),
  signal(4, {
    key: "trusted-business-fields",
    chapter: "V2",
    asvsSections: ["V2.3", "V2.4"],
    severity: "medium",
    cwe: "CWE-602",
    cvss: 6.5,
    category: "Validation and Business Logic",
    title: "권한·가격 같은 중요 값이 클라이언트 입력에서 결정됩니다",
    titleKo: "중요 비즈니스 값 서버 검증 누락",
    impact: "클라이언트 요청을 조작해 관리자 권한, 소유자, 가격 또는 결제 상태를 바꿀 수 있습니다.",
    remediation: "권한과 가격 등 중요 값은 인증 세션과 서버 데이터에서 다시 계산하세요.",
    pattern: /(?:role|isAdmin|ownerId|userId|price|amount|paid|status)\s*[:=].*(?:req\.body|body\.|payload\.|formData|searchParams)/i,
  }),
  signal(5, {
    key: "blank-opener",
    chapter: "V3",
    asvsSections: ["V3.2"],
    severity: "low",
    cwe: "CWE-1022",
    cvss: 3.1,
    category: "Web Frontend Security",
    title: "새 창 링크가 원래 페이지를 조작할 수 있습니다",
    titleKo: "탭내빙 방어 누락",
    impact: "외부 페이지가 window.opener를 이용해 원래 탭을 피싱 페이지로 바꿀 수 있습니다.",
    remediation: "target=\"_blank\" 링크에 rel=\"noopener noreferrer\"를 추가하세요.",
    pattern: /target\s*=\s*["'{]?_blank/i,
    safeWindowPattern: /rel\s*=\s*["'{][^\n}]*(?:noopener|noreferrer)/i,
    filePattern: /\.(?:tsx?|jsx?|html|vue|svelte)$/i,
  }),
  signal(6, {
    key: "postmessage-wildcard",
    chapter: "V3",
    asvsSections: ["V3.4"],
    severity: "medium",
    cwe: "CWE-346",
    cvss: 5.4,
    category: "Web Frontend Security",
    title: "브라우저 메시지가 모든 출처로 전송됩니다",
    titleKo: "postMessage 출처 제한 누락",
    impact: "민감한 브라우저 메시지가 공격자 출처로 전달될 수 있습니다.",
    remediation: "postMessage의 대상 출처를 정확한 HTTPS origin으로 고정하세요.",
    pattern: /\.postMessage\s*\([^\n]*,\s*["'`]\*["'`]\s*\)/i,
  }),
  signal(7, {
    key: "message-origin",
    chapter: "V3",
    asvsSections: ["V3.4"],
    severity: "medium",
    cwe: "CWE-346",
    cvss: 5.4,
    category: "Web Frontend Security",
    title: "message 이벤트 처리 전에 발신 출처를 확인하지 않습니다",
    titleKo: "브라우저 메시지 origin 검증 누락",
    impact: "악성 사이트가 보낸 메시지가 신뢰된 명령처럼 처리될 수 있습니다.",
    remediation: "event.origin과 event.source를 허용 목록으로 검증한 뒤 메시지를 처리하세요.",
    pattern: /addEventListener\s*\(\s*["']message["']/i,
    safeContentPattern: /(?:event|e)\.origin\s*(?:===|!==)|allowedOrigins?\.includes/i,
  }),
  signal(8, {
    key: "browser-token-storage",
    chapter: "V3",
    asvsSections: ["V3.5"],
    severity: "medium",
    cwe: "CWE-922",
    cvss: 5.4,
    category: "Web Frontend Security",
    title: "인증 토큰이 브라우저 스크립트 저장소에 보관됩니다",
    titleKo: "민감 토큰 localStorage 저장",
    impact: "XSS가 발생하면 장기 인증 토큰을 쉽게 탈취할 수 있습니다.",
    remediation: "가능하면 HttpOnly·Secure·SameSite 쿠키 기반 세션을 사용하세요.",
    pattern: /(?:localStorage|sessionStorage)\.setItem\s*\(\s*["'`](?:token|accessToken|refreshToken|jwt|session)/i,
  }),
  signal(9, {
    key: "cors-credentials-wildcard",
    chapter: "V4",
    asvsSections: ["V4.1", "V4.2"],
    severity: "high",
    cwe: "CWE-942",
    cvss: 8.1,
    category: "API and Web Service",
    title: "인증정보를 허용하면서 CORS 출처가 과도하게 열려 있습니다",
    titleKo: "위험한 CORS 설정",
    impact: "공격자 사이트가 로그인된 사용자의 권한으로 API 응답을 읽을 수 있습니다.",
    remediation: "허용 origin을 명시적으로 제한하고 요청 origin을 그대로 반사하지 마세요.",
    pattern: /(?:origin\s*:\s*["'`]\*["'`]|Access-Control-Allow-Origin["'`\s,:]+\*)/i,
    requiresContent: /(?:credentials\s*:\s*true|Access-Control-Allow-Credentials["'`\s,:]+true)/i,
  }),
  signal(10, {
    key: "graphql-dev-features",
    chapter: "V4",
    asvsSections: ["V4.3"],
    severity: "low",
    cwe: "CWE-215",
    cvss: 3.7,
    category: "API and Web Service",
    title: "운영 GraphQL 서버에서 탐색·디버그 기능이 활성화되어 있습니다",
    titleKo: "GraphQL 개발 기능 노출",
    impact: "API 스키마와 공격 가능한 필드를 쉽게 열거할 수 있습니다.",
    remediation: "운영 환경에서는 playground와 불필요한 introspection을 비활성화하세요.",
    pattern: /(?:introspection|playground|graphiql)\s*:\s*true/i,
    requiresContent: /graphql|apollo|mercurius/i,
  }),
  signal(11, {
    key: "unbounded-json-body",
    chapter: "V4",
    asvsSections: ["V4.4"],
    severity: "low",
    cwe: "CWE-770",
    cvss: 3.7,
    category: "API and Web Service",
    title: "API 요청 본문 크기 제한이 명시되지 않았습니다",
    titleKo: "요청 크기 제한 누락",
    impact: "매우 큰 요청이 메모리와 CPU를 소모해 서비스 지연을 유발할 수 있습니다.",
    remediation: "JSON·폼 파서에 업무상 필요한 최대 크기 제한을 설정하세요.",
    pattern: /(?:express|app|router)\.json\s*\(\s*\)|bodyParser\.json\s*\(\s*\)/i,
    safeWindowPattern: /limit\s*:/i,
  }),
  signal(12, {
    key: "upload-original-name",
    chapter: "V5",
    asvsSections: ["V5.2", "V5.3"],
    severity: "high",
    cwe: "CWE-434",
    cvss: 7.5,
    category: "File Handling",
    title: "업로드 파일명이 검증 없이 저장 경로에 사용됩니다",
    titleKo: "안전하지 않은 파일 업로드 경로",
    impact: "조작된 파일명으로 허용 경로 밖에 파일을 덮어쓰거나 실행 파일을 저장할 수 있습니다.",
    remediation: "서버가 무작위 파일명을 생성하고 MIME·확장자·크기·실제 내용을 함께 검증하세요.",
    pattern: /(?:originalname|originalFilename|file\.name).*(?:writeFile|move|rename|join|destination)|(?:writeFile|move|rename|join)[^(]*\([^\n]*(?:originalname|originalFilename|file\.name)/i,
    safeWindowPattern: /(?:basename|randomUUID|uuid|sanitize|allowedTypes|mime)/i,
    windowBefore: 4,
    windowAfter: 2,
  }),
  signal(13, {
    key: "archive-extract-all",
    chapter: "V5",
    asvsSections: ["V5.4"],
    severity: "high",
    cwe: "CWE-22",
    cvss: 7.5,
    category: "File Handling",
    title: "압축 파일을 경로 검증 없이 한꺼번에 풉니다",
    titleKo: "Zip Slip 경로 검증 누락",
    impact: "악성 압축 파일이 대상 디렉터리 밖의 파일을 덮어쓸 수 있습니다.",
    remediation: "각 엔트리의 정규화된 경로가 대상 디렉터리 내부인지 확인한 뒤 추출하세요.",
    pattern: /(?:extractAllTo|extractall|unzipper\.Extract|admZip\.extractAllTo)\s*\(/i,
    safeWindowPattern: /(?:resolve|normalize|startsWith|\.\.\/|isWithin)/i,
    windowBefore: 5,
  }),
  signal(14, {
    key: "weak-password-hash",
    chapter: "V6",
    asvsSections: ["V6.2", "V6.3"],
    severity: "critical",
    cwe: "CWE-916",
    cvss: 9.1,
    category: "Authentication",
    title: "비밀번호에 빠른 범용 해시를 사용합니다",
    titleKo: "취약한 비밀번호 해싱",
    impact: "비밀번호 DB가 유출되면 공격자가 대량으로 원문 비밀번호를 복구하기 쉽습니다.",
    remediation: "Argon2id, scrypt 또는 적절한 비용의 bcrypt/PBKDF2와 개별 salt를 사용하세요.",
    pattern: /(?:md5|sha1|sha256|sha512|createHash\s*\(\s*["'`](?:md5|sha1|sha256|sha512))[^(\n]*(?:password|passwd|pwd)/i,
  }),
  signal(15, {
    key: "plaintext-password-compare",
    chapter: "V6",
    asvsSections: ["V6.2"],
    severity: "critical",
    cwe: "CWE-256",
    cvss: 9.1,
    category: "Authentication",
    title: "비밀번호를 평문으로 직접 비교합니다",
    titleKo: "평문 비밀번호 처리",
    impact: "저장소나 로그가 노출되면 사용자 비밀번호가 즉시 유출됩니다.",
    remediation: "비밀번호 해시 라이브러리의 상수 시간 verify 함수를 사용하세요.",
    pattern: /(?:password|passwd|pwd)\s*(?:===|==)\s*(?:req\.body|body\.|input\.|user\.(?:password|passwd|pwd))/i,
    excludeLinePattern: /(?:hash|digest|bcrypt|argon|scrypt|verify|compare)/i,
  }),
  signal(16, {
    key: "auth-no-throttle",
    chapter: "V6",
    asvsSections: ["V6.4"],
    severity: "medium",
    cwe: "CWE-307",
    cvss: 6.5,
    category: "Authentication",
    title: "로그인 처리 코드에 요청 제한 흔적이 없습니다",
    titleKo: "로그인 무차별 대입 방어 누락",
    impact: "공격자가 비밀번호를 반복 대입하거나 유출된 계정 목록을 자동 시험할 수 있습니다.",
    remediation: "계정·IP 기반 속도 제한, 지연, 모니터링과 단계적 추가 인증을 적용하세요.",
    pattern: /(?:signIn|signin|login|authenticate)\s*(?:=|\(|:)|export\s+(?:async\s+)?function\s+POST/i,
    filePattern: /(?:auth|login|signin|session)[^/]*\.(?:tsx?|jsx?|py|go|rb|php|java|cs)$/i,
    safeContentPattern: /(?:rateLimit|rateLimiter|throttl|tooMany|429|lockout|attempts?)/i,
  }),
  signal(17, {
    key: "cookie-flags",
    chapter: "V7",
    asvsSections: ["V7.2", "V7.4"],
    severity: "medium",
    cwe: "CWE-614",
    cvss: 5.4,
    category: "Session Management",
    title: "세션 쿠키에 필수 보안 속성이 모두 보이지 않습니다",
    titleKo: "세션 쿠키 보안 속성 누락",
    impact: "스크립트나 평문 연결, 교차 사이트 요청을 통해 세션이 탈취·오용될 가능성이 커집니다.",
    remediation: "세션 쿠키에 HttpOnly, Secure, 적절한 SameSite와 제한된 Path를 설정하세요.",
    pattern: /(?:cookies?\.set|setCookie|Set-Cookie)[^(\n]*\([^\n]*(?:session|token|auth|sid)/i,
    safeWindowPattern: /httpOnly\s*:\s*true[\s\S]*secure\s*:\s*true[\s\S]*sameSite|secure\s*:\s*true[\s\S]*httpOnly\s*:\s*true[\s\S]*sameSite/i,
    windowAfter: 6,
  }),
  signal(18, {
    key: "token-in-url",
    chapter: "V7",
    asvsSections: ["V7.5"],
    severity: "high",
    cwe: "CWE-598",
    cvss: 7.5,
    category: "Session Management",
    title: "세션·인증 토큰이 URL에 포함됩니다",
    titleKo: "URL을 통한 세션 토큰 노출",
    impact: "토큰이 브라우저 기록, 프록시 로그, 분석 도구와 Referer 헤더에 남을 수 있습니다.",
    remediation: "세션 토큰은 URL이 아니라 안전한 쿠키 또는 Authorization 헤더로 전달하세요.",
    pattern: /(?:[?&](?:token|access_token|session|jwt)=|searchParams\.(?:set|append)\s*\(\s*["'`](?:token|access_token|session|jwt))/i,
  }),
  signal(19, {
    key: "mutation-no-auth",
    chapter: "V8",
    asvsSections: ["V8.2", "V8.3"],
    severity: "medium",
    cwe: "CWE-862",
    cvss: 6.5,
    category: "Authorization",
    title: "데이터 변경 API에서 서버 권한 확인 흔적을 찾지 못했습니다",
    titleKo: "변경 API 권한 확인 누락 가능성",
    impact: "인증되지 않거나 권한이 부족한 사용자가 데이터를 생성·수정·삭제할 수 있습니다.",
    remediation: "모든 변경 핸들러에서 서버 세션과 대상 리소스 권한을 명시적으로 확인하세요.",
    pattern: /export\s+(?:async\s+)?function\s+(?:POST|PUT|PATCH|DELETE)\b|router\.(?:post|put|patch|delete)\s*\(/i,
    filePattern: /(?:route|api|controller|handler|server)[^/]*\.(?:tsx?|jsx?|py|go|rb|php|java|cs)$/i,
    safeContentPattern: /(?:getCurrentUser|getServerSession|auth\s*\(|requireAuth|authorize|permission|currentUser|req\.user|session\.user|userId|ownerId|403|Unauthorized|Forbidden)/i,
  }),
  signal(20, {
    key: "client-admin-gate",
    chapter: "V8",
    asvsSections: ["V8.1", "V8.4"],
    severity: "high",
    cwe: "CWE-602",
    cvss: 7.5,
    category: "Authorization",
    title: "관리자 권한이 브라우저 상태만으로 결정됩니다",
    titleKo: "클라이언트 전용 관리자 권한 검사",
    impact: "브라우저 저장값이나 UI 상태를 조작해 관리자 기능에 접근할 수 있습니다.",
    remediation: "UI 검사는 보조 수단으로만 쓰고 API에서 관리자 권한을 다시 확인하세요.",
    pattern: /(?:localStorage|sessionStorage).*(?:isAdmin|role|admin)|(?:isAdmin|role)\s*=.*(?:localStorage|sessionStorage)/i,
  }),
  signal(21, {
    key: "jwt-decode-only",
    chapter: "V9",
    asvsSections: ["V9.1", "V9.2"],
    severity: "critical",
    cwe: "CWE-345",
    cvss: 9.1,
    category: "Self-contained Tokens",
    title: "JWT 서명을 검증하지 않고 내용만 해석합니다",
    titleKo: "JWT 서명 검증 누락",
    impact: "공격자가 위조한 토큰의 사용자·권한 정보를 서버가 신뢰할 수 있습니다.",
    remediation: "신뢰한 키와 허용 알고리즘을 지정해 verify한 뒤 issuer, audience, 만료를 검사하세요.",
    pattern: /(?:jwt\.)?decode\s*\([^)]*(?:token|jwt|authorization)/i,
    safeWindowPattern: /(?:jwt\.)?verify\s*\(/i,
    windowBefore: 4,
    windowAfter: 4,
  }),
  signal(22, {
    key: "jwt-algorithms",
    chapter: "V9",
    asvsSections: ["V9.1"],
    severity: "high",
    cwe: "CWE-347",
    cvss: 7.5,
    category: "Self-contained Tokens",
    title: "JWT 검증 시 허용 알고리즘을 고정하지 않았습니다",
    titleKo: "JWT 알고리즘 제한 누락",
    impact: "라이브러리 설정에 따라 약한 알고리즘이나 알고리즘 혼동 공격이 가능해질 수 있습니다.",
    remediation: "verify 호출에 허용 algorithms 목록을 명시하고 토큰 헤더의 선택을 신뢰하지 마세요.",
    pattern: /(?:jwt\.)?verify\s*\([^\n]+\)/i,
    safeWindowPattern: /algorithms?\s*:/i,
    windowAfter: 3,
  }),
  signal(23, {
    key: "oauth-missing-state",
    chapter: "V10",
    asvsSections: ["V10.3", "V10.4"],
    severity: "high",
    cwe: "CWE-352",
    cvss: 7.5,
    category: "OAuth and OIDC",
    title: "OAuth 인증 요청에 state 또는 nonce 보호가 보이지 않습니다",
    titleKo: "OAuth 요청 위조 방어 누락",
    impact: "로그인 CSRF나 인증 응답 바꿔치기로 공격자 계정이 연결될 수 있습니다.",
    remediation: "예측 불가능하고 세션에 결합된 state를 사용하고 OIDC에서는 nonce도 검증하세요.",
    pattern: /(?:response_type=code|\/authorize\?|authorizationUrl)/i,
    requiresContent: /oauth|oidc|openid|authorization/i,
    safeContentPattern: /(?:state|nonce)\s*[:=]|[?&](?:state|nonce)=/i,
  }),
  signal(24, {
    key: "oauth-no-pkce",
    chapter: "V10",
    asvsSections: ["V10.2", "V10.4"],
    severity: "medium",
    cwe: "CWE-345",
    cvss: 6.5,
    category: "OAuth and OIDC",
    title: "OAuth authorization code 흐름에 PKCE 사용 흔적이 없습니다",
    titleKo: "OAuth PKCE 누락",
    impact: "가로챈 authorization code가 다른 클라이언트에서 재사용될 수 있습니다.",
    remediation: "S256 code_challenge와 일회성 code_verifier를 사용하세요.",
    pattern: /response_type\s*[=:]\s*["'`]code|response_type=code/i,
    requiresContent: /oauth|oidc|openid|authorize/i,
    safeContentPattern: /code_challenge|code_verifier|pkce/i,
  }),
  signal(25, {
    key: "weak-crypto",
    chapter: "V11",
    asvsSections: ["V11.2", "V11.3"],
    severity: "high",
    cwe: "CWE-327",
    cvss: 7.5,
    category: "Cryptography",
    title: "보안 용도에 폐기된 암호 알고리즘을 사용합니다",
    titleKo: "취약한 암호 알고리즘",
    impact: "해시 충돌이나 약한 암호화로 무결성 또는 기밀성이 깨질 수 있습니다.",
    remediation: "용도에 맞는 최신 알고리즘과 검증된 고수준 암호 라이브러리를 사용하세요.",
    pattern: /(?:createHash|createCipheriv|Cipher|getInstance)\s*\(\s*["'`](?:md5|sha-?1|des|rc4|aes[^"'`]*ecb)/i,
  }),
  signal(26, {
    key: "security-math-random",
    chapter: "V11",
    asvsSections: ["V11.1"],
    severity: "high",
    cwe: "CWE-338",
    cvss: 7.5,
    category: "Cryptography",
    title: "보안 토큰을 예측 가능한 난수로 생성합니다",
    titleKo: "보안 난수 생성기 미사용",
    impact: "공격자가 비밀번호 재설정 토큰, OTP 또는 세션 값을 예측할 수 있습니다.",
    remediation: "crypto.randomBytes, randomUUID 또는 플랫폼 CSPRNG를 사용하세요.",
    pattern: /(?:token|otp|nonce|secret|session|reset|code)\w*\s*=.*Math\.random\s*\(|Math\.random\s*\([^\n]*(?:token|otp|nonce|secret|session|reset)/i,
  }),
  signal(27, {
    key: "fixed-iv",
    chapter: "V11",
    asvsSections: ["V11.3"],
    severity: "high",
    cwe: "CWE-329",
    cvss: 7.5,
    category: "Cryptography",
    title: "암호화 초기화 벡터가 고정값으로 보입니다",
    titleKo: "고정 IV 사용",
    impact: "같은 평문 패턴이 반복 노출되어 암호문의 기밀성이 약해질 수 있습니다.",
    remediation: "암호화마다 CSPRNG로 새 nonce/IV를 만들고 인증 암호 모드를 사용하세요.",
    pattern: /(?:createCipheriv|AES\.new|Cipher\.getInstance)[^\n]*(?:Buffer\.alloc\([^)]*,\s*0\)|["'`](?:0{12,}|[0-9a-f]{16,})["'`])/i,
  }),
  signal(28, {
    key: "tls-validation-disabled",
    chapter: "V12",
    asvsSections: ["V12.2", "V12.3"],
    severity: "critical",
    cwe: "CWE-295",
    cvss: 9.1,
    category: "Secure Communication",
    title: "TLS 인증서 검증이 비활성화되어 있습니다",
    titleKo: "TLS 인증서 검증 비활성화",
    impact: "중간자 공격자가 서버를 사칭해 인증정보와 데이터를 가로챌 수 있습니다.",
    remediation: "인증서 검증을 켜고 필요한 경우 신뢰할 CA 또는 인증서 핀을 안전하게 구성하세요.",
    pattern: /rejectUnauthorized\s*:\s*false|verify\s*=\s*False|CERT_NONE|InsecureSkipVerify\s*:\s*true|NODE_TLS_REJECT_UNAUTHORIZED\s*=\s*["']?0/i,
  }),
  signal(29, {
    key: "plaintext-service-url",
    chapter: "V12",
    asvsSections: ["V12.1"],
    severity: "medium",
    cwe: "CWE-319",
    cvss: 6.5,
    category: "Secure Communication",
    title: "외부 서비스 통신에 평문 HTTP 또는 WebSocket을 사용합니다",
    titleKo: "평문 외부 통신",
    impact: "네트워크 구간에서 요청·응답과 인증정보가 탈취되거나 변조될 수 있습니다.",
    remediation: "외부 통신은 https:// 또는 wss://를 사용하고 TLS를 강제하세요.",
    pattern: /["'`](?:http|ws):\/\/(?!localhost|127\.0\.0\.1|0\.0\.0\.0|\[::1\])[^"'`\s]+/i,
    excludeLinePattern: /(?:example\.com|schema|namespace|xmlns|documentation|comment)/i,
  }),
  signal(30, {
    key: "production-debug",
    chapter: "V13",
    asvsSections: ["V13.1", "V13.4"],
    severity: "medium",
    cwe: "CWE-489",
    cvss: 5.3,
    category: "Configuration",
    title: "디버그 또는 상세 오류 기능이 활성화되어 있습니다",
    titleKo: "운영 디버그 설정 활성화",
    impact: "스택, 경로, 환경값과 내부 구조가 사용자에게 노출될 수 있습니다.",
    remediation: "운영 구성에서는 debug, dev mode, detailed errors와 playground를 비활성화하세요.",
    pattern: /(?:DEBUG|debug|devTools|detailedErrors|showStack|stacktrace)\s*[:=]\s*(?:true|True|1|["']true["'])/i,
    filePattern: /(?:config|settings|\.env|application|next\.config|vite\.config|server)[^/]*$/i,
  }),
  signal(31, {
    key: "production-sourcemap",
    chapter: "V13",
    asvsSections: ["V13.1"],
    severity: "low",
    cwe: "CWE-540",
    cvss: 3.7,
    category: "Configuration",
    title: "운영 클라이언트 소스맵이 공개될 수 있습니다",
    titleKo: "운영 소스맵 노출",
    impact: "원본 소스와 내부 경로가 노출되어 공격 분석이 쉬워질 수 있습니다.",
    remediation: "공개 배포에서는 브라우저 소스맵을 끄거나 접근이 제한된 오류 수집 서비스에만 업로드하세요.",
    pattern: /(?:productionBrowserSourceMaps|sourcemap|sourceMap)\s*[:=]\s*true/i,
    filePattern: /(?:config|settings|next|vite|webpack|rollup)[^/]*\.(?:tsx?|jsx?|json|ya?ml|toml)$/i,
  }),
  signal(32, {
    key: "default-credential",
    chapter: "V13",
    asvsSections: ["V13.2"],
    severity: "critical",
    cwe: "CWE-1392",
    cvss: 9.8,
    category: "Configuration",
    title: "기본·예제 계정 비밀번호가 운영 코드에 남아 있습니다",
    titleKo: "기본 인증정보 사용",
    impact: "공격자가 공개적으로 알려진 값으로 관리자나 데이터베이스에 로그인할 수 있습니다.",
    remediation: "기본 계정을 제거하고 배포 시 강한 비밀값을 별도 비밀 저장소에서 주입하세요.",
    pattern: /(?:password|passwd|pwd)\s*[:=]\s*["'`](?:admin|password|changeme|default|root|test123|123456)["'`]/i,
  }),
  signal(33, {
    key: "sensitive-log",
    chapter: "V14",
    asvsSections: ["V14.2", "V14.3"],
    severity: "high",
    cwe: "CWE-532",
    cvss: 7.5,
    category: "Data Protection",
    title: "로그에 비밀번호·토큰·개인정보가 기록될 수 있습니다",
    titleKo: "민감정보 로그 기록",
    impact: "로그 접근 권한이 있는 사용자나 외부 로그 서비스에 인증정보와 개인정보가 노출됩니다.",
    remediation: "민감 필드를 제거·마스킹하고 구조화 로그에 허용한 필드만 기록하세요.",
    pattern: /(?:console\.(?:log|info|debug|error)|logger\.(?:info|debug|error|warn)|print\s*\()[^\n]*(?:password|passwd|token|authorization|cookie|secret|ssn|credit.?card)/i,
  }),
  signal(34, {
    key: "pii-query-string",
    chapter: "V14",
    asvsSections: ["V14.1", "V14.2"],
    severity: "medium",
    cwe: "CWE-598",
    cvss: 5.3,
    category: "Data Protection",
    title: "민감정보가 URL 쿼리 문자열에 포함됩니다",
    titleKo: "URL 내 민감정보 노출",
    impact: "민감 값이 브라우저 기록, 접근 로그, 분석 서비스와 Referer에 남을 수 있습니다.",
    remediation: "민감정보는 요청 본문으로 보내고 로그·분석 수집에서 제거하세요.",
    pattern: /[?&](?:password|passwd|token|secret|ssn|credit_?card|resident_?number)=|searchParams\.(?:set|append)\s*\(\s*["'`](?:password|passwd|secret|ssn|credit_?card)/i,
  }),
  signal(35, {
    key: "unsafe-deserialization",
    chapter: "V15",
    asvsSections: ["V15.3"],
    severity: "critical",
    cwe: "CWE-502",
    cvss: 9.8,
    category: "Secure Coding and Architecture",
    title: "신뢰할 수 없는 데이터를 안전하지 않게 역직렬화합니다",
    titleKo: "안전하지 않은 역직렬화",
    impact: "조작된 데이터가 객체 생성 과정에서 임의 코드 실행이나 권한 상승을 일으킬 수 있습니다.",
    remediation: "안전한 데이터 형식과 엄격한 스키마를 사용하고 네이티브 객체 역직렬화를 피하세요.",
    pattern: /(?:pickle\.loads|yaml\.load\s*\(|unserialize\s*\(|ObjectInputStream\s*\(|BinaryFormatter|Marshal\.load)\s*[^\n]*(?:req|request|body|input|data|payload|file)/i,
  }),
  signal(36, {
    key: "dynamic-ssrf",
    chapter: "V15",
    asvsSections: ["V15.4"],
    severity: "high",
    cwe: "CWE-918",
    cvss: 8.2,
    category: "Secure Coding and Architecture",
    title: "사용자 입력 URL로 서버가 직접 외부 요청을 보냅니다",
    titleKo: "SSRF 가능성",
    impact: "공격자가 내부 서비스, 클라우드 메타데이터 또는 제한된 네트워크에 대신 접근시킬 수 있습니다.",
    remediation: "목적지 scheme·host·port를 허용 목록으로 제한하고 DNS 재바인딩과 사설 IP를 차단하세요.",
    pattern: /(?:fetch|axios\.(?:get|post|request)|requests?\.(?:get|post)|http\.(?:get|request))\s*\([^\n]*(?:req\.|request\.|params|query|body|input|url)/i,
    safeWindowPattern: /(?:allowlist|allowedHosts|safeFetch|isPrivate|isBlocked|new URL|validateUrl)/i,
    windowBefore: 5,
  }),
  signal(37, {
    key: "prototype-pollution",
    chapter: "V15",
    asvsSections: ["V15.2"],
    severity: "high",
    cwe: "CWE-1321",
    cvss: 8.1,
    category: "Secure Coding and Architecture",
    title: "요청 객체를 기존 객체에 재귀 병합합니다",
    titleKo: "프로토타입 오염 가능성",
    impact: "__proto__ 같은 키로 애플리케이션 전체 객체의 기본 속성을 변조할 수 있습니다.",
    remediation: "요청 키를 스키마로 제한하고 안전한 병합 라이브러리와 null prototype 객체를 사용하세요.",
    pattern: /(?:merge|defaultsDeep|deepMerge|Object\.assign)\s*\([^\n]*(?:req\.body|body|payload|input)/i,
    safeWindowPattern: /(?:schema|safeParse|validate|sanitize|__proto__|constructor|prototype)/i,
    windowBefore: 4,
  }),
  signal(38, {
    key: "error-stack-response",
    chapter: "V16",
    asvsSections: ["V16.1", "V16.2"],
    severity: "medium",
    cwe: "CWE-209",
    cvss: 5.3,
    category: "Security Logging and Error Handling",
    title: "내부 오류 메시지나 스택이 API 응답으로 전달됩니다",
    titleKo: "상세 오류정보 노출",
    impact: "파일 경로, 쿼리, 라이브러리와 내부 구조가 노출되어 후속 공격에 활용될 수 있습니다.",
    remediation: "사용자에게는 일반 오류 코드만 반환하고 상세 원인은 접근 통제된 서버 로그에 기록하세요.",
    pattern: /(?:res\.(?:json|send)|NextResponse\.json|Response\.json|return\s+json)\s*\([^\n]*(?:error|err)\.(?:stack|message|cause)/i,
  }),
  signal(39, {
    key: "empty-catch",
    chapter: "V16",
    asvsSections: ["V16.1"],
    severity: "low",
    cwe: "CWE-390",
    cvss: 3.3,
    category: "Security Logging and Error Handling",
    title: "오류를 기록하거나 처리하지 않고 무시합니다",
    titleKo: "빈 예외 처리",
    impact: "보안 실패와 공격 흔적이 감춰지고 애플리케이션이 잘못된 상태로 계속 동작할 수 있습니다.",
    remediation: "예상 오류만 구분해 처리하고 보안 이벤트는 민감정보 없이 구조화해 기록하세요.",
    pattern: /catch\s*(?:\([^)]*\))?\s*\{\s*\}/i,
  }),
  signal(40, {
    key: "webrtc-insecure-signaling",
    chapter: "V17",
    asvsSections: ["V17.3"],
    severity: "high",
    cwe: "CWE-319",
    cvss: 7.5,
    category: "WebRTC",
    title: "WebRTC 시그널링이 암호화되지 않은 채널을 사용합니다",
    titleKo: "WebRTC 평문 시그널링",
    impact: "세션 설명과 ICE 후보가 가로채이거나 변조되어 통화 연결이 탈취될 수 있습니다.",
    remediation: "인증된 wss:// 또는 HTTPS 시그널링을 사용하고 메시지 권한과 무결성을 검증하세요.",
    pattern: /["'`]ws:\/\/[^"'`\s]+/i,
    requiresContent: /RTCPeerConnection|getUserMedia|iceCandidate|RTCSessionDescription|webrtc/i,
  }),
  signal(41, {
    key: "webrtc-hardcoded-turn",
    chapter: "V17",
    asvsSections: ["V17.2", "V17.3"],
    severity: "high",
    cwe: "CWE-798",
    cvss: 7.5,
    category: "WebRTC",
    title: "TURN 서버 인증정보가 클라이언트 코드에 고정되어 있습니다",
    titleKo: "WebRTC TURN 인증정보 노출",
    impact: "제3자가 TURN 릴레이를 무단 사용해 비용과 서비스 장애를 유발할 수 있습니다.",
    remediation: "짧은 수명의 TURN 자격증명을 인증된 서버에서 동적으로 발급하세요.",
    pattern: /(?:iceServers|turn:)[\s\S]{0,300}username\s*:[\s\S]{0,120}credential\s*:\s*["'`][^"'`]+["'`]/i,
    requiresContent: /RTCPeerConnection|iceServers|turn:/i,
  }),
];

export const ASVS5_RULE_IDS = ASVS5_STATIC_SIGNALS.map((s) => s.ruleId);

export const ASVS5_RULES: SecurityRule[] = ASVS5_STATIC_SIGNALS.map((s) => ({
  id: s.ruleId,
  family: s.ruleId,
  version: ASVS_VERSION,
  // 소스만 읽는 정적 신호이므로 모드 A(상위 모드 B/C에도 포함).
  mode: "A" as const,
  title: s.title,
  titleKo: s.titleKo,
  summaryKo: s.impact,
  severity: s.severity,
  standards: [
    ...s.asvsSections.map((id) => ({
      framework: "OWASP_ASVS" as const,
      version: ASVS_VERSION,
      id,
    })),
    { framework: "CWE" as const, id: s.cwe },
  ],
  appliesTo: ["web", "api", "baas"],
  selector: {
    all: [{ field: "source.access", op: "equals", value: "read_only" }],
  },
  methods: ["SAST"],
  prerequisites: { SAST: ["source_checkout"] },
  checks: [
    {
      id: `scan-${s.key}`,
      toolId: "static_web_analyzer",
      method: "SAST",
    },
  ],
  execution: {
    tier: "PASSIVE",
    target: "source_checkout",
    destructiveOperations: false,
  },
  remediation: {
    autoPatch: "branch_only",
    allowedPaths: ["app/**", "src/**", "server/**", "api/**", "config/**", "*.config.*"],
    productionChange: "not_applicable",
  },
  verificationRequiredChecks: [`scan-${s.key}`, "changed-code-scan"],
}));

const RULE_BY_KEY = new Map(ASVS5_STATIC_SIGNALS.map((s) => [s.key, s.ruleId]));

export function asvsRuleIdForSignal(key: string): string | null {
  return RULE_BY_KEY.get(key) ?? null;
}
