// Builds the bundled sample apps from samples/<name>/ (the single source of truth):
//   - src/lib/samples/<name>.generated.ts  (files the "샘플로 체험하기" button uses)
//   - <name>-sample.zip at the repo root   (the same files, for the ZIP upload flow)
// Run: npm run samples. A test fails if the generated module drifts from the folder.
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { makeZip } from "@/lib/remediation/artifactBuilder";
import { readSampleDir } from "@/lib/samples/readSampleDir";

const ROOT = process.cwd();

const SAMPLES = [{ name: "memo-board", exportName: "MEMO_BOARD_FILES" }];

for (const { name, exportName } of SAMPLES) {
  const files = readSampleDir(ROOT, name);
  const moduleText = `// GENERATED by scripts/samples/build-samples.mts from samples/${name}/. Do not edit; run \`npm run samples\`.
export const ${exportName}: Record<string, string> = ${JSON.stringify(files, null, 2)};
`;
  writeFileSync(path.join(ROOT, "src/lib/samples", `${name}.generated.ts`), moduleText);
  const zip = makeZip(files);
  writeFileSync(path.join(ROOT, `${name}-sample.zip`), zip);
  mkdirSync(path.join(ROOT, "public/samples"), { recursive: true });
  writeFileSync(path.join(ROOT, "public/samples", `${name}-sample.zip`), zip);
  console.log(`${name}: ${Object.keys(files).length} files → src/lib/samples/${name}.generated.ts, ${name}-sample.zip, public/samples/${name}-sample.zip`);
}
